name: ds18b20
description: Driver for the DS18B20 temperature sensor.
environment:
  sdk: ^2.0.0-alpha.144
dependencies:
  one_wire:
    url: github.com/toitware/toit-1-wire
    version: ^2.1.0
  sensors:
    path: ../toit-sensors
